# 0-2 numpy 문제풀이

In [2]:
import numpy as np

In [80]:
# slicing 문제 : 다음의 데이터를 추철하는 하는 코드를 작성하시오.
datas = [[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]]

arr = np.array(datas)
arr[:,-1]

array([11, 45, 82])

In [ ]:

---------------------
# 출력 결과: 
array([11, 45, 82])

In [ ]:
# numpy함수를 이용하여 10이하의 짝수와 홀수 각각의 리스트를 생성하고, 이 두가지 리스트를 사용하여 2차원의 데이터를 만들어라.

---------------------
# 출력 결과: 
array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [20]:
ODD = np.arange(1, 10+1, 2)
EVEN = np.arange(2, 10+1, 2)
result = np.vstack((ODD, EVEN))
result

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

### 10부터 30까지 정수로 이루어진 1차원배열을 만든다음 2차원  (7, -1) 형태로 변환하시오.
- 그리고 최댓값과 최솟값을 구하시오.

In [30]:
X = np.arange(10, 30+1)
print(X.reshape(7, -1))

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]


In [27]:
MAX = X.max()
print(f'max:{MAX}')

max:30


In [29]:
MIN = X.min()
print(f'min:{MIN}')

min:10


In [ ]:
출력결과 :
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]

max: 30
min: 10

### 문제: 아래 배열을 3행 4열 형태로 reshape 하시오. 변환된 배열에서 마지막 행만 출력하시오.

In [31]:
datas = [[10, 20, 30, 40, 50, 60],
         [70, 80, 90, 100, 110, 120]]

In [37]:
datas = np.array(datas)

In [44]:
DATAS = datas.reshape(4, 3)
result = sorted(DATAS.tolist())

In [45]:
print(result[3])

[100, 110, 120]


### 코드와 그  출력값이 다음과 같을 때 0.6664104711248381을 출력하는 코드를 작성하시오.

In [47]:
import random

In [48]:
random.seed(12)

In [49]:
print(random.random())

0.4745706786885481


In [50]:
print(random.random())

0.6574725026572553


In [51]:
print(random.random())

0.6664104711248381


In [52]:
print(random.random())

0.14260035292536777


In [58]:
if random.random() ==! 0.6664104711248381:
    continue
elif random.random() == 0.6664104711248381::
    print(random.random()) 
    break

print(random.random())

SyntaxError: invalid syntax (2919464107.py, line 1)

In [ ]:
-----------------------
0.4745706786885481
0.6574725026572553
0.6664104711248381
0.14260035292536777

### seed값을 5로 고정한 후 random.randint(1,11)을 세번 실행했을 때 나오는 값을 구하시오.

In [64]:
random.seed(5)

In [65]:
random.randint(1,11)

10

In [66]:
random.randint(1,11)

5

In [67]:
random.randint(1,11)

6

### (1) 1~25까지 step이 3개인 1차원의 배열을 만들고,
### (2) reshape을 이용하여 3x3행렬로 만드시오.

In [71]:
y = np.arange(1, 25+1, 3)
y.reshape(3,3)

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [ ]:
----------------------
출력결과
(1)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])
(2) 
array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [75]:
# arr의 각 행에서 최댓값만 추출하여 1차원 배열 형태로 출력하시오.
# ---------------------
import numpy as np

np.random.seed(11)
arr = np.random.random((4, 5))
arr

array([[0.18026969, 0.01947524, 0.46321853, 0.72493393, 0.4202036 ],
       [0.4854271 , 0.01278081, 0.48737161, 0.94180665, 0.85079509],
       [0.72996447, 0.10873607, 0.89390417, 0.85715425, 0.16508662],
       [0.63233401, 0.02048361, 0.11673727, 0.31636731, 0.15791231]])

In [77]:
arr.max(axis=1)

array([0.72493393, 0.94180665, 0.89390417, 0.63233401])